---
- name: Test role
  hosts: 127.0.0.1
  connection: local
  become: true

  vars_files:
    - defaults/main.yml

  tasks:
  - name: apt | Check updates
    block:
    - name: Get available updates
      ansible.builtin.command: apt list --upgradable -a
      register: updates
    - name: Assert
      ansible.builtin.assert:
        that: updates.stdout_lines | count == 1
    when: ansible_pkg_mgr == 'apt'

  - name: yum | Check updates
    block:
    - name: Get available updates
      ansible.builtin.command: yum check-update
      register: updates
      ignore_errors: yes
    - debug:
        var: updates
    - name: Assert
      ansible.builtin.assert:
        that: updates.rc == 0
    when: ansible_pkg_mgr == 'yum'

  - name: dnf | Check updates
    block:
    - name: Get available updates
      ansible.builtin.command: dnf check-update
      register: updates
      ignore_errors: yes
    - name: Assert
      ansible.builtin.assert:
        that: updates.rc == 0
    when: ansible_pkg_mgr == 'dnf'
