---
- ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- ansible.builtin.include_tasks: reboot.yml
  when: upgrade_packages_reboot_if_needed|bool == true and reboot_required|default(false)|bool == true
