---
- name: DNF update the system
  ansible.builtin.dnf:
    name:  "*"
    state: latest
  when: upgrade_packages_all|bool == true and ansible_facts['pkg_mgr'] == 'dnf'

- name: Add needs-restarting utility
  ansible.builtin.dnf:
    name: dnf-utils
    state: latest
  when: upgrade_packages_reboot_if_needed|bool == true and ansible_facts['pkg_mgr'] == 'dnf'

- name: Yum update the system
  ansible.builtin.yum:
    name: "*"
    state: latest
  when: upgrade_packages_all|bool == true and ansible_facts['pkg_mgr'] == 'yum'

- name: Add needs-restarting utility
  ansible.builtin.yum:
    name: yum-utils
    state: latest
  when: upgrade_packages_reboot_if_needed|bool == true and ansible_facts['pkg_mgr'] == 'yum'

- name: Reboot required
  ansible.builtin.command: "/usr/bin/needs-restarting -r"
  register: reboot_required
  ignore_errors: True
  changed_when: False
  failed_when: reboot_required.rc == 2
  when: upgrade_packages_reboot_if_needed|bool == true

- name: Set reboot_required variable
  ansible.builtin.set_fact:
    reboot_required: true
  when: upgrade_packages_reboot_if_needed|bool == true and reboot_required.rc == 1
