---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false

  tasks:
  - name:
    command: apt list --upgradable
    register: updates
  - debug: var=updates.stdout_lines
  - name: Example assertion
    ansible.builtin.assert:
      that: true

